// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: internal/node/proto/stats.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatType int32

const (
	StatType_Outbounds StatType = 0
	StatType_Outbound  StatType = 1
	StatType_Inbounds  StatType = 2
	StatType_Inbound   StatType = 3
	StatType_UsersStat StatType = 4
	StatType_UserStat  StatType = 5
)

// Enum value maps for StatType.
var (
	StatType_name = map[int32]string{
		0: "Outbounds",
		1: "Outbound",
		2: "Inbounds",
		3: "Inbound",
		4: "UsersStat",
		5: "UserStat",
	}
	StatType_value = map[string]int32{
		"Outbounds": 0,
		"Outbound":  1,
		"Inbounds":  2,
		"Inbound":   3,
		"UsersStat": 4,
		"UserStat":  5,
	}
)

func (x StatType) Enum() *StatType {
	p := new(StatType)
	*p = x
	return p
}

func (x StatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_node_proto_stats_proto_enumTypes[0].Descriptor()
}

func (StatType) Type() protoreflect.EnumType {
	return &file_internal_node_proto_stats_proto_enumTypes[0]
}

func (x StatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatType.Descriptor instead.
func (StatType) EnumDescriptor() ([]byte, []int) {
	return file_internal_node_proto_stats_proto_rawDescGZIP(), []int{0}
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Reset_        bool                   `protobuf:"varint,2,opt,name=reset,proto3" json:"reset,omitempty"`
	Type          StatType               `protobuf:"varint,3,opt,name=type,proto3,enum=common.StatType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_internal_node_proto_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_node_proto_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_internal_node_proto_stats_proto_rawDescGZIP(), []int{0}
}

func (x *StatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatRequest) GetReset_() bool {
	if x != nil {
		return x.Reset_
	}
	return false
}

func (x *StatRequest) GetType() StatType {
	if x != nil {
		return x.Type
	}
	return StatType_Outbounds
}

type Stat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Link          string                 `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	Value         int64                  `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stat) Reset() {
	*x = Stat{}
	mi := &file_internal_node_proto_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stat) ProtoMessage() {}

func (x *Stat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_node_proto_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stat.ProtoReflect.Descriptor instead.
func (*Stat) Descriptor() ([]byte, []int) {
	return file_internal_node_proto_stats_proto_rawDescGZIP(), []int{1}
}

func (x *Stat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stat) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Stat) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Stat) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*Stat                `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_internal_node_proto_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_node_proto_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_internal_node_proto_stats_proto_rawDescGZIP(), []int{2}
}

func (x *StatResponse) GetStats() []*Stat {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_internal_node_proto_stats_proto protoreflect.FileDescriptor

const file_internal_node_proto_stats_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/node/proto/stats.proto\x12\x06common\"]\n" +
	"\vStatRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05reset\x18\x02 \x01(\bR\x05reset\x12$\n" +
	"\x04type\x18\x03 \x01(\x0e2\x10.common.StatTypeR\x04type\"X\n" +
	"\x04Stat\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04link\x18\x03 \x01(\tR\x04link\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x03R\x05value\"2\n" +
	"\fStatResponse\x12\"\n" +
	"\x05stats\x18\x01 \x03(\v2\f.common.StatR\x05stats*_\n" +
	"\bStatType\x12\r\n" +
	"\tOutbounds\x10\x00\x12\f\n" +
	"\bOutbound\x10\x01\x12\f\n" +
	"\bInbounds\x10\x02\x12\v\n" +
	"\aInbound\x10\x03\x12\r\n" +
	"\tUsersStat\x10\x04\x12\f\n" +
	"\bUserStat\x10\x05B?Z=github.com/pasarguard/pasarguard-exporter/internal/node/protob\x06proto3"

var (
	file_internal_node_proto_stats_proto_rawDescOnce sync.Once
	file_internal_node_proto_stats_proto_rawDescData []byte
)

func file_internal_node_proto_stats_proto_rawDescGZIP() []byte {
	file_internal_node_proto_stats_proto_rawDescOnce.Do(func() {
		file_internal_node_proto_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_node_proto_stats_proto_rawDesc), len(file_internal_node_proto_stats_proto_rawDesc)))
	})
	return file_internal_node_proto_stats_proto_rawDescData
}

var file_internal_node_proto_stats_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_node_proto_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_node_proto_stats_proto_goTypes = []any{
	(StatType)(0),        // 0: common.StatType
	(*StatRequest)(nil),  // 1: common.StatRequest
	(*Stat)(nil),         // 2: common.Stat
	(*StatResponse)(nil), // 3: common.StatResponse
}
var file_internal_node_proto_stats_proto_depIdxs = []int32{
	0, // 0: common.StatRequest.type:type_name -> common.StatType
	2, // 1: common.StatResponse.stats:type_name -> common.Stat
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_node_proto_stats_proto_init() }
func file_internal_node_proto_stats_proto_init() {
	if File_internal_node_proto_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_node_proto_stats_proto_rawDesc), len(file_internal_node_proto_stats_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_node_proto_stats_proto_goTypes,
		DependencyIndexes: file_internal_node_proto_stats_proto_depIdxs,
		EnumInfos:         file_internal_node_proto_stats_proto_enumTypes,
		MessageInfos:      file_internal_node_proto_stats_proto_msgTypes,
	}.Build()
	File_internal_node_proto_stats_proto = out.File
	file_internal_node_proto_stats_proto_goTypes = nil
	file_internal_node_proto_stats_proto_depIdxs = nil
}
